In [9]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://runiq:runiq@localhost:5432/runiq")
df = pd.read_sql("SELECT * FROM activities_raw", engine)
df

,id,user_id,imported_at,source,garmin_activity_id,api_activity_name,api_activity_type,api_event_type,api_start_time_local,api_start_time_gmt,...,api_hr_time_in_zone_5,api_power_time_in_zone_1,api_power_time_in_zone_2,api_power_time_in_zone_3,api_power_time_in_zone_4,api_power_time_in_zone_5,api_is_favorite,api_is_pr,api_device_id,api_manufacturer
0,ff0cdb7a-3dd4-4505-902b-dc5b68a916fa,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175287,garmin_api,24369012997,Treadmill Running,treadmill_running,uncategorized,2026-09-15 18:56:43,2026-09-15 10:56:43,...,0.000,64.998,1.000,0.000,0.000,0.000,False,False,3524639758,GARMIN
1,579307e3-b330-4379-8861-160b19ba0e51,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175293,garmin_api,24327210043,Kuala Lumpur Running,running,uncategorized,2026-09-12 05:43:54,2026-09-11 21:43:54,...,0.000,393.991,0.000,0.000,0.000,0.000,False,False,3524639758,GARMIN
2,028c4a99-6dfe-4eb2-8385-bbea5306a988,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175296,garmin_api,24315897370,Kuala Lumpur Running,running,uncategorized,2026-09-11 06:27:12,2026-09-10 22:27:12,...,0.000,1122.043,2.999,0.000,0.000,0.000,False,False,3524639758,GARMIN
3,a6d45e37-065f-400c-9e92-e0df067adc98,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175299,garmin_api,24304956583,Treadmill Running,treadmill_running,uncategorized,2026-09-10 12:15:33,2026-09-10 04:15:33,...,0.000,88.987,14.001,0.000,0.000,0.000,False,False,3524639758,GARMIN
4,4006480a-3da2-4a04-8659-f27002e0a07f,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175300,garmin_api,24292566213,Treadmill Running,treadmill_running,uncategorized,2026-09-09 12:33:45,2026-09-09 04:33:45,...,0.000,193.303,24.000,0.000,0.000,0.000,False,False,3524639758,GARMIN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,ae675ab5-590a-4bfa-986a-0807f43beabd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175521,garmin_api,21481902289,Shah Alam Running,running,uncategorized,2026-01-08 20:42:38,2026-01-08 12:42:38,...,265.424,1711.388,1.999,0.000,0.000,0.000,False,False,3524639758,GARMIN
149,67bc0bcb-3d82-4b86-b14e-2d55fc2e699e,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175523,garmin_api,21470473805,Kuala Lumpur Running,running,uncategorized,2026-01-07 18:57:57,2026-01-07 10:57:57,...,0.000,174.992,42.653,29.000,23.000,4.000,False,False,3524639758,GARMIN
150,ca911597-5b82-47de-ae2e-2b8dd813a404,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175524,garmin_api,21459847472,Kuala Lumpur Running,running,uncategorized,2026-01-06 18:25:26,2026-01-06 10:25:26,...,0.000,241.992,89.014,54.006,38.992,14.997,False,False,3524639758,GARMIN
151,d60de702-03f4-4e51-ba03-880c14d2d55a,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175525,garmin_api,21448662338,Kuala Lumpur Running,running,uncategorized,2026-01-05 18:19:51,2026-01-05 10:19:51,...,0.000,752.911,208.994,100.003,83.998,85.997,False,True,3524639758,GARMIN
152,3e9cfb80-ebfa-4005-92e4-435b203428cd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-17 05:15:38.146071,garmin_api,24382041101,Treadmill Running,treadmill_running,uncategorized,2026-09-16 18:35:20,2026-09-16 10:35:20,...,0.000,0.000,0.000,0.000,0.000,0.000,False,False,3524639758,GARMIN

In [10]:
# remove non running records
df = df[(df['api_activity_type'] == 'running') | (df['api_activity_type'] == 'treadmill_running')]
df

,id,user_id,imported_at,source,garmin_activity_id,api_activity_name,api_activity_type,api_event_type,api_start_time_local,api_start_time_gmt,...,api_hr_time_in_zone_5,api_power_time_in_zone_1,api_power_time_in_zone_2,api_power_time_in_zone_3,api_power_time_in_zone_4,api_power_time_in_zone_5,api_is_favorite,api_is_pr,api_device_id,api_manufacturer
0,ff0cdb7a-3dd4-4505-902b-dc5b68a916fa,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175287,garmin_api,24369012997,Treadmill Running,treadmill_running,uncategorized,2026-09-15 18:56:43,2026-09-15 10:56:43,...,0.000,64.998,1.000,0.000,0.000,0.000,False,False,3524639758,GARMIN
1,579307e3-b330-4379-8861-160b19ba0e51,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175293,garmin_api,24327210043,Kuala Lumpur Running,running,uncategorized,2026-09-12 05:43:54,2026-09-11 21:43:54,...,0.000,393.991,0.000,0.000,0.000,0.000,False,False,3524639758,GARMIN
2,028c4a99-6dfe-4eb2-8385-bbea5306a988,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175296,garmin_api,24315897370,Kuala Lumpur Running,running,uncategorized,2026-09-11 06:27:12,2026-09-10 22:27:12,...,0.000,1122.043,2.999,0.000,0.000,0.000,False,False,3524639758,GARMIN
3,a6d45e37-065f-400c-9e92-e0df067adc98,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175299,garmin_api,24304956583,Treadmill Running,treadmill_running,uncategorized,2026-09-10 12:15:33,2026-09-10 04:15:33,...,0.000,88.987,14.001,0.000,0.000,0.000,False,False,3524639758,GARMIN
4,4006480a-3da2-4a04-8659-f27002e0a07f,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175300,garmin_api,24292566213,Treadmill Running,treadmill_running,uncategorized,2026-09-09 12:33:45,2026-09-09 04:33:45,...,0.000,193.303,24.000,0.000,0.000,0.000,False,False,3524639758,GARMIN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,ae675ab5-590a-4bfa-986a-0807f43beabd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175521,garmin_api,21481902289,Shah Alam Running,running,uncategorized,2026-01-08 20:42:38,2026-01-08 12:42:38,...,265.424,1711.388,1.999,0.000,0.000,0.000,False,False,3524639758,GARMIN
149,67bc0bcb-3d82-4b86-b14e-2d55fc2e699e,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175523,garmin_api,21470473805,Kuala Lumpur Running,running,uncategorized,2026-01-07 18:57:57,2026-01-07 10:57:57,...,0.000,174.992,42.653,29.000,23.000,4.000,False,False,3524639758,GARMIN
150,ca911597-5b82-47de-ae2e-2b8dd813a404,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175524,garmin_api,21459847472,Kuala Lumpur Running,running,uncategorized,2026-01-06 18:25:26,2026-01-06 10:25:26,...,0.000,241.992,89.014,54.006,38.992,14.997,False,False,3524639758,GARMIN
151,d60de702-03f4-4e51-ba03-880c14d2d55a,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175525,garmin_api,21448662338,Kuala Lumpur Running,running,uncategorized,2026-01-05 18:19:51,2026-01-05 10:19:51,...,0.000,752.911,208.994,100.003,83.998,85.997,False,True,3524639758,GARMIN
152,3e9cfb80-ebfa-4005-92e4-435b203428cd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-17 05:15:38.146071,garmin_api,24382041101,Treadmill Running,treadmill_running,uncategorized,2026-09-16 18:35:20,2026-09-16 10:35:20,...,0.000,0.000,0.000,0.000,0.000,0.000,False,False,3524639758,GARMIN

In [11]:
# EDA
# df = df.apply(pd.to_numeric, errors='coerce')
# df_nontreadmill = df[df['location'] != 'Treadmill']
# df_nontreadmill
# df_nontreadmill.describe(include='all')

# api_average_running_cadence
# cadence have to split to easyrun/recovery & speed, can separate by api_training_effect_label

In [12]:
# extract location data
df['location'] = df['api_activity_name'].str.replace('Running', '').str.strip()
df['location'] = df['location'].str.split('-').str[0].str.strip()
df

,id,user_id,imported_at,source,garmin_activity_id,api_activity_name,api_activity_type,api_event_type,api_start_time_local,api_start_time_gmt,...,api_power_time_in_zone_1,api_power_time_in_zone_2,api_power_time_in_zone_3,api_power_time_in_zone_4,api_power_time_in_zone_5,api_is_favorite,api_is_pr,api_device_id,api_manufacturer,location
0,ff0cdb7a-3dd4-4505-902b-dc5b68a916fa,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175287,garmin_api,24369012997,Treadmill Running,treadmill_running,uncategorized,2026-09-15 18:56:43,2026-09-15 10:56:43,...,64.998,1.000,0.000,0.000,0.000,False,False,3524639758,GARMIN,Treadmill
1,579307e3-b330-4379-8861-160b19ba0e51,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175293,garmin_api,24327210043,Kuala Lumpur Running,running,uncategorized,2026-09-12 05:43:54,2026-09-11 21:43:54,...,393.991,0.000,0.000,0.000,0.000,False,False,3524639758,GARMIN,Kuala Lumpur
2,028c4a99-6dfe-4eb2-8385-bbea5306a988,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175296,garmin_api,24315897370,Kuala Lumpur Running,running,uncategorized,2026-09-11 06:27:12,2026-09-10 22:27:12,...,1122.043,2.999,0.000,0.000,0.000,False,False,3524639758,GARMIN,Kuala Lumpur
3,a6d45e37-065f-400c-9e92-e0df067adc98,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175299,garmin_api,24304956583,Treadmill Running,treadmill_running,uncategorized,2026-09-10 12:15:33,2026-09-10 04:15:33,...,88.987,14.001,0.000,0.000,0.000,False,False,3524639758,GARMIN,Treadmill
4,4006480a-3da2-4a04-8659-f27002e0a07f,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175300,garmin_api,24292566213,Treadmill Running,treadmill_running,uncategorized,2026-09-09 12:33:45,2026-09-09 04:33:45,...,193.303,24.000,0.000,0.000,0.000,False,False,3524639758,GARMIN,Treadmill
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,ae675ab5-590a-4bfa-986a-0807f43beabd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175521,garmin_api,21481902289,Shah Alam Running,running,uncategorized,2026-01-08 20:42:38,2026-01-08 12:42:38,...,1711.388,1.999,0.000,0.000,0.000,False,False,3524639758,GARMIN,Shah Alam
149,67bc0bcb-3d82-4b86-b14e-2d55fc2e699e,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175523,garmin_api,21470473805,Kuala Lumpur Running,running,uncategorized,2026-01-07 18:57:57,2026-01-07 10:57:57,...,174.992,42.653,29.000,23.000,4.000,False,False,3524639758,GARMIN,Kuala Lumpur
150,ca911597-5b82-47de-ae2e-2b8dd813a404,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175524,garmin_api,21459847472,Kuala Lumpur Running,running,uncategorized,2026-01-06 18:25:26,2026-01-06 10:25:26,...,241.992,89.014,54.006,38.992,14.997,False,False,3524639758,GARMIN,Kuala Lumpur
151,d60de702-03f4-4e51-ba03-880c14d2d55a,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175525,garmin_api,21448662338,Kuala Lumpur Running,running,uncategorized,2026-01-05 18:19:51,2026-01-05 10:19:51,...,752.911,208.994,100.003,83.998,85.997,False,True,3524639758,GARMIN,Kuala Lumpur
152,3e9cfb80-ebfa-4005-92e4-435b203428cd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-17 05:15:38.146071,garmin_api,24382041101,Treadmill Running,treadmill_running,uncategorized,2026-09-16 18:35:20,2026-09-16 10:35:20,...,0.000,0.000,0.000,0.000,0.000,False,False,3524639758,GARMIN,Treadmill

In [13]:
# compute pace
import math
df['pace_mm'] = (df['api_duration']/60) / (df['api_distance']/1000)
df['mm'] = df['pace_mm'].apply(math.floor)
df['ss'] = ((df['pace_mm'] - df['mm']) * 60).apply(math.floor)
df['pace'] = df['mm'].astype(str) + ':' + df['ss'].astype(str).str.zfill(2)
df

,id,user_id,imported_at,source,garmin_activity_id,api_activity_name,api_activity_type,api_event_type,api_start_time_local,api_start_time_gmt,...,api_power_time_in_zone_5,api_is_favorite,api_is_pr,api_device_id,api_manufacturer,location,pace_mm,mm,ss,pace
0,ff0cdb7a-3dd4-4505-902b-dc5b68a916fa,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175287,garmin_api,24369012997,Treadmill Running,treadmill_running,uncategorized,2026-09-15 18:56:43,2026-09-15 10:56:43,...,0.000,False,False,3524639758,GARMIN,Treadmill,7.985468,7,59,7:59
1,579307e3-b330-4379-8861-160b19ba0e51,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175293,garmin_api,24327210043,Kuala Lumpur Running,running,uncategorized,2026-09-12 05:43:54,2026-09-11 21:43:54,...,0.000,False,False,3524639758,GARMIN,Kuala Lumpur,6.600415,6,36,6:36
2,028c4a99-6dfe-4eb2-8385-bbea5306a988,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175296,garmin_api,24315897370,Kuala Lumpur Running,running,uncategorized,2026-09-11 06:27:12,2026-09-10 22:27:12,...,0.000,False,False,3524639758,GARMIN,Kuala Lumpur,6.528094,6,31,6:31
3,a6d45e37-065f-400c-9e92-e0df067adc98,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175299,garmin_api,24304956583,Treadmill Running,treadmill_running,uncategorized,2026-09-10 12:15:33,2026-09-10 04:15:33,...,0.000,False,False,3524639758,GARMIN,Treadmill,7.711822,7,42,7:42
4,4006480a-3da2-4a04-8659-f27002e0a07f,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175300,garmin_api,24292566213,Treadmill Running,treadmill_running,uncategorized,2026-09-09 12:33:45,2026-09-09 04:33:45,...,0.000,False,False,3524639758,GARMIN,Treadmill,7.461755,7,27,7:27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,ae675ab5-590a-4bfa-986a-0807f43beabd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175521,garmin_api,21481902289,Shah Alam Running,running,uncategorized,2026-01-08 20:42:38,2026-01-08 12:42:38,...,0.000,False,False,3524639758,GARMIN,Shah Alam,5.715748,5,42,5:42
149,67bc0bcb-3d82-4b86-b14e-2d55fc2e699e,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175523,garmin_api,21470473805,Kuala Lumpur Running,running,uncategorized,2026-01-07 18:57:57,2026-01-07 10:57:57,...,4.000,False,False,3524639758,GARMIN,Kuala Lumpur,8.668684,8,40,8:40
150,ca911597-5b82-47de-ae2e-2b8dd813a404,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175524,garmin_api,21459847472,Kuala Lumpur Running,running,uncategorized,2026-01-06 18:25:26,2026-01-06 10:25:26,...,14.997,False,False,3524639758,GARMIN,Kuala Lumpur,8.537337,8,32,8:32
151,d60de702-03f4-4e51-ba03-880c14d2d55a,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175525,garmin_api,21448662338,Kuala Lumpur Running,running,uncategorized,2026-01-05 18:19:51,2026-01-05 10:19:51,...,85.997,False,True,3524639758,GARMIN,Kuala Lumpur,5.788825,5,47,5:47
152,3e9cfb80-ebfa-4005-92e4-435b203428cd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-17 05:15:38.146071,garmin_api,24382041101,Treadmill Running,treadmill_running,uncategorized,2026-09-16 18:35:20,2026-09-16 10:35:20,...,0.000,False,False,3524639758,GARMIN,Treadmill,6.899380,6,53,6:53

# **OpenWeather API**

In [14]:
from datetime import datetime
import pytz

def myt2unix(tt):
    malaysia_tz = pytz.timezone('Asia/Kuala_Lumpur')

    # Parse the string to datetime, then localize to Malaysia time
    dt = datetime.strptime(tt, '%Y-%m-%d %H:%M:%S')
    dt_malaysia = malaysia_tz.localize(dt)

    # Convert to Unix timestamp
    unix_time = int(dt_malaysia.timestamp())
    return unix_time

df['dt_unix'] = df['api_start_time_local'].apply(myt2unix)
df

,id,user_id,imported_at,source,garmin_activity_id,api_activity_name,api_activity_type,api_event_type,api_start_time_local,api_start_time_gmt,...,api_is_favorite,api_is_pr,api_device_id,api_manufacturer,location,pace_mm,mm,ss,pace,dt_unix
0,ff0cdb7a-3dd4-4505-902b-dc5b68a916fa,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175287,garmin_api,24369012997,Treadmill Running,treadmill_running,uncategorized,2026-09-15 18:56:43,2026-09-15 10:56:43,...,False,False,3524639758,GARMIN,Treadmill,7.985468,7,59,7:59,1789469803
1,579307e3-b330-4379-8861-160b19ba0e51,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175293,garmin_api,24327210043,Kuala Lumpur Running,running,uncategorized,2026-09-12 05:43:54,2026-09-11 21:43:54,...,False,False,3524639758,GARMIN,Kuala Lumpur,6.600415,6,36,6:36,1789163034
2,028c4a99-6dfe-4eb2-8385-bbea5306a988,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175296,garmin_api,24315897370,Kuala Lumpur Running,running,uncategorized,2026-09-11 06:27:12,2026-09-10 22:27:12,...,False,False,3524639758,GARMIN,Kuala Lumpur,6.528094,6,31,6:31,1789079232
3,a6d45e37-065f-400c-9e92-e0df067adc98,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175299,garmin_api,24304956583,Treadmill Running,treadmill_running,uncategorized,2026-09-10 12:15:33,2026-09-10 04:15:33,...,False,False,3524639758,GARMIN,Treadmill,7.711822,7,42,7:42,1789013733
4,4006480a-3da2-4a04-8659-f27002e0a07f,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175300,garmin_api,24292566213,Treadmill Running,treadmill_running,uncategorized,2026-09-09 12:33:45,2026-09-09 04:33:45,...,False,False,3524639758,GARMIN,Treadmill,7.461755,7,27,7:27,1788928425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,ae675ab5-590a-4bfa-986a-0807f43beabd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175521,garmin_api,21481902289,Shah Alam Running,running,uncategorized,2026-01-08 20:42:38,2026-01-08 12:42:38,...,False,False,3524639758,GARMIN,Shah Alam,5.715748,5,42,5:42,1767876158
149,67bc0bcb-3d82-4b86-b14e-2d55fc2e699e,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175523,garmin_api,21470473805,Kuala Lumpur Running,running,uncategorized,2026-01-07 18:57:57,2026-01-07 10:57:57,...,False,False,3524639758,GARMIN,Kuala Lumpur,8.668684,8,40,8:40,1767783477
150,ca911597-5b82-47de-ae2e-2b8dd813a404,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175524,garmin_api,21459847472,Kuala Lumpur Running,running,uncategorized,2026-01-06 18:25:26,2026-01-06 10:25:26,...,False,False,3524639758,GARMIN,Kuala Lumpur,8.537337,8,32,8:32,1767695126
151,d60de702-03f4-4e51-ba03-880c14d2d55a,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175525,garmin_api,21448662338,Kuala Lumpur Running,running,uncategorized,2026-01-05 18:19:51,2026-01-05 10:19:51,...,False,True,3524639758,GARMIN,Kuala Lumpur,5.788825,5,47,5:47,1767608391
152,3e9cfb80-ebfa-4005-92e4-435b203428cd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-17 05:15:38.146071,garmin_api,24382041101,Treadmill Running,treadmill_running,uncategorized,2026-09-16 18:35:20,2026-09-16 10:35:20,...,False,False,3524639758,GARMIN,Treadmill,6.899380,6,53,6:53,1789554920

In [15]:
import requests

tt_unix = df.loc[1, 'dt_unix']
lat = round(df.loc[1, 'api_start_latitude'], 4)
lon = round(df.loc[1, 'api_start_longitude'], 4)
API_KEY = "867473ff72aa87abf0739682654da3ce"
# city = "Kuala Lumpur"

url = "https://api.openweathermap.org/data/4.0/onecall/timeline/1h?"
params = {
    # "q": city,
    "appid": API_KEY,
    "lat":lat,
    "lon":lon,
    # "type":'hour',
    "start":tt_unix
}

response = requests.get(url, params=params)

if response.status_code == 200:
    data = response.json()

data

{'lat': 3.1432,
 'lon': 101.6845,
 'timezone': 'Asia/Kuala_Lumpur',
 'timezone_offset': 28800,
 'data': [{'dt': 1789164000,
   'temp': 298.7,
   'feels_like': 299.48,
   'pressure': 1011,
   'humidity': 83,
   'dew_point': 295.6,
   'uvi': 0,
   'clouds': 100,
   'visibility': 10000,
   'wind_speed': 1.54,
   'wind_deg': 140,
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'rain': {'1h': 0.49}},
  {'dt': 1789167600,
   'temp': 297.93,
   'feels_like': 298.76,
   'pressure': 1012,
   'humidity': 88,
   'dew_point': 295.81,
   'uvi': 0,
   'clouds': 100,
   'visibility': 10000,
   'wind_speed': 1.54,
   'wind_deg': 0,
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'rain': {'1h': 0.5}},
  {'dt': 1789171200,
   'temp': 298.7,
   'feels_like': 299.48,
   'pressure': 1011,
   'humidity': 83,
   'dew_point': 295.6,
   'uvi': 0,
   'clouds': 100,
   'visibility': 10000,
   'wind_speed': 0,
   'wind_deg': 0,
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'rain': {'1h': 0.33}},
  {'dt': 1789174800,
   'temp': 299.76,
   'feels_like': 299.76,
   'pressure': 1011,
   'humidity': 74,
   'dew_point': 294.74,
   'uvi': 0,
   'clouds': 100,
   'visibility': 10000,
   'wind_speed': 2.06,
   'wind_deg': 130,
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'rain': {'1h': 0.33}},
  {'dt': 1789178400,
   'temp': 300.05,
   'feels_like': 303.9,
   'pressure': 1012,
   'humidity': 93,
   'dew_point': 298.82,
   'uvi': 0,
   'clouds': 100,
   'visibility': 10000,
   'wind_speed': 3.23,
   'wind_deg': 89,
   'wind_gust': 3.42,
   'weather': [{'id': 502,
     'main': 'Rain',
     'description': 'heavy intensity rain',
     'icon': '10d'}],
   'rain': {'1h': 5.08}},
  {'dt': 1789182000,
   'temp': 300.05,
   'feels_like': 303.9,
   'pressure': 1012,
   'humidity': 93,
   'dew_point': 298.82,
   'uvi': 0,
   'clouds': 100,
   'visibility': 10000,
   'wind_speed': 3.23,
   'wind_deg': 89,
   'wind_gust': 3.42,
   'weather': [{'id': 502,
     'main': 'Rain',
     'description': 'heavy intensity rain',
     'icon': '10d'}],
   'rain': {'1h': 5.08}},
  {'dt': 1789185600,
   'temp': 300.05,
   'feels_like': 303.9,
   'pressure': 1012,
   'humidity': 93,
   'dew_point': 298.82,
   'uvi': 0,
   'clouds': 100,
   'visibility': 10000,
   'wind_speed': 3.23,
   'wind_deg': 89,
   'wind_gust': 3.42,
   'weather': [{'id': 502,
     'main': 'Rain',
     'description': 'heavy intensity rain',
     'icon': '10d'}],
   'rain': {'1h': 5.08}},
  {'dt': 1789189200,
   'temp': 300.38,
   'feels_like': 301.29,
   'pressure': 1010,
   'humidity': 57,
   'dew_point': 291.12,
   'uvi': 0,
   'clouds': 100,
   'visibility': 10000,
   'wind_speed': 3.24,
   'wind_deg': 128,
   'wind_gust': 4.01,
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}]},
  {'dt': 1789192800,
   'temp': 300.16,
   'feels_like': 302.63,
   'pressure': 1010,
   'humidity': 77,
   'dew_point': 295.78,
   'uvi': 0,
   'clouds': 100,
   'visibility': 10000,
   'wind_speed': 3.24,
   'wind_deg': 128,
   'wind_gust': 4.01,
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}]},
  {'dt': 1789196400,
   'temp': 300.47,
   'feels_like': 300.81,
   'pressure': 1010,
   'humidity': 49,
   'dew_point': 288.83,
   'uvi': 0,
   'clouds': 100,
   'visibility': 10000,
   'wind_speed': 3.24,
   'wind_deg': 128,
   'wind_gust': 4.01,
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}]},
  {'dt': 1789200000,
   'temp': 302.34,
   'feels_like': 306.49,
   'pressure': 1008,
   'humidity': 71,
   'dew_point': 296.54,
   'uvi': 0,
   'clouds': 95,
   'visibility': 10000,
   'wind_speed': 5.58,
   'wind_deg': 140,
   'wind_gust': 6.03,
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}]},
  {'dt': 1789203600,
   'temp': 302.82,
   'feels_like': 307.62,
   'pressure': 1008,
   'humidity': 71,
   'dew_point': 297,
   'uvi': 0,
   'clouds': 95,
   'visibility': 10000,
   'wind_speed': 5.58,
   'wind_deg': 140,
   'wind_gust': 6.03,
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}]},
  {'dt': 1789207200,
   'temp': 303.03,
   'feels_like': 305.38,
   'pressure': 1008,
   'humidity': 58,
   'dew_point': 293.87,
   'uvi': 0,
   'clouds': 95,
   'visibility': 10000,
   'wind_speed': 5.14,
   'wind_deg': 170,
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}]},
  {'dt': 1789210800,
   'temp': 300.44,
   'feels_like': 302.9,
   'pressure': 1009,
   'humidity': 74,
   'dew_point': 295.4,
   'uvi': 0,
   'clouds': 99,
   'visibility': 10000,
   'wind_speed': 4.12,
   'wind_deg': 190,
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}]},
  {'dt': 1789214400,
   'temp': 300.44,
   'feels_like': 302.9,
   'pressure': 1009,
   'humidity': 74,
   'dew_point': 295.4,
   'uvi': 0,
   'clouds': 99,
   'visibility': 10000,
   'wind_speed': 3.6,
   'wind_deg': 180,
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}]},
  {'dt': 1789218000,
   'temp': 299.91,
   'feels_like': 302.21,
   'pressure': 1009,
   'humidity': 78,
   'dew_point': 295.75,
   'uvi': 0,
   'clouds': 99,
   'visibility': 10000,
   'wind_speed': 2.57,
   'wind_deg': 180,
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}]},
  {'dt': 1789221600,
   'temp': 299.34,
   'feels_like': 299.34,
   'pressure': 1011,
   'humidity': 78,
   'dew_point': 295.2,
   'uvi': 0,
   'clouds': 79,
   'visibility': 10000,
   'wind_speed': 1.54,
   'wind_deg': 0,
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'rain': {'1h': 0.4}},
  {'dt': 1789225200,
   'temp': 299.02,
   'feels_like': 299.7,
   'pressure': 1011,
   'humidity': 78,
   'dew_point': 294.89,
   'uvi': 0,
   'clouds': 79,
   'visibility': 10000,
   'wind_speed': 1.03,
   'wind_deg': 0,
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'rain': {'1h': 0.4}},
  {'dt': 1789228800,
   'temp': 298.7,
   'feels_like': 299.61,
   'pressure': 1011,
   'humidity': 88,
   'dew_point': 296.56,
   'uvi': 0,
   'clouds': 79,
   'visibility': 10000,
   'wind_speed': 1.03,
   'wind_deg': 0,
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'rain': {'1h': 0.4}},
  {'dt': 1789232400,
   'temp': 298.36,
   'feels_like': 299.1,
   'pressure': 1010,
   'humidity': 83,
   'dew_point': 295.27,
   'uvi': 0,
   'clouds': 96,
   'visibility': 10000,
   'wind_speed': 1.03,
   'wind_deg': 0,
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}]}],
 'prev': 'http://api.openweathermap.org/data/4.0/onecall/timeline/1h?cnt=20&lat=3.1432&lon=101.6845&start=1789092000&appid=867473ff72aa87abf0739682654da3ce',
 'next': 'http://api.openweathermap.org/data/4.0/onecall/timeline/1h?cnt=20&lat=3.1432&lon=101.6845&start=1789236000&appid=867473ff72aa87abf0739682654da3ce'}

In [16]:
import time

df = df.reset_index(drop=True)

yes = 0
results = []
call_count = 0  # ✅ track API calls

for i in range(len(df)):
    if pd.notna(df.loc[i, 'api_start_latitude']):
        tt_unix = df.loc[i, 'dt_unix']
        lat = round(df.loc[i, 'api_start_latitude'], 4)
        lon = round(df.loc[i, 'api_start_longitude'], 4)
        API_KEY = "867473ff72aa87abf0739682654da3ce"

        url = "https://api.openweathermap.org/data/4.0/onecall/timeline/1h?"
        params = {
            "appid": API_KEY,
            "lat": lat,
            "lon": lon,
            "dt": tt_unix
        }

        # ✅ Pause every 50 calls
        if call_count > 0 and call_count % 50 == 0:
            print(f"Reached {call_count} calls — waiting 60 seconds...")
            time.sleep(60)
            print("Resuming...")

        try:
            response = requests.get(url, params=params, timeout=10)
            if response.status_code == 200:
                data = response.json()
                hourly_list = data.get('data', [])
                
                # ✅ Find the entry where dt matches tt_unix (or closest one)
                matched = None
                for entry in hourly_list:
                    if entry['dt'] == tt_unix:
                        matched = entry
                        break
                
                # If no exact match, pick the closest dt
                if matched is None and hourly_list:
                    matched = min(hourly_list, key=lambda x: abs(x['dt'] - tt_unix))

                if matched:
                    results.append({
                        'index': i,
                        'weather_dt': matched.get('dt'),
                        'weather_temp': matched.get('temp'),
                        'weather_feels_like': matched.get('feels_like'),
                        'weather_pressure': matched.get('pressure'),
                        'weather_humidity': matched.get('humidity'),
                        'weather_dew_point': matched.get('dew_point'),
                        'weather_uvi': matched.get('uvi'),
                        'weather_clouds': matched.get('clouds'),
                        'weather_visibility': matched.get('visibility'),
                        'weather_wind_speed': matched.get('wind_speed'),
                        'weather_wind_deg': matched.get('wind_deg'),
                        'weather_wind_gust': matched.get('wind_gust'),          # may be None if absent
                        'weather_main': matched.get('weather', [{}])[0].get('main'),
                        'weather_description': matched.get('weather', [{}])[0].get('description'),
                        'weather_rain_1h': matched.get('rain', {}).get('1h'),   # None if no rain
                    })
                    yes += 1
                else:
                    results.append({'index': i, 'weather_dt': None, 'weather_temp': None,
                                    'weather_feels_like': None, 'weather_pressure': None,
                                    'weather_humidity': None, 'weather_dew_point': None,
                                    'weather_uvi': None, 'weather_clouds': None,
                                    'weather_visibility': None, 'weather_wind_speed': None,
                                    'weather_wind_deg': None, 'weather_wind_gust': None,
                                    'weather_main': None, 'weather_description': None,
                                    'weather_rain_1h': None})
            # if response.status_code == 200:
            #     data = response.json()
            #     hourly = data.get('data', [{}])[0]
            #     results.append({
            #         'index': i,
            #         'weather_temp': hourly.get('temp'),
            #         'weather_humidity': hourly.get('humidity'),
            #         'weather_description': hourly.get('weather', [{}])[0].get('description'),
            #     })
            #     yes += 1
            # else:
            #     print(f"Row {i}: API error {response.status_code}")
            #     results.append({'index': i, 'weather_temp': None, 'weather_humidity': None, 'weather_description': None})

        except requests.exceptions.ConnectTimeout:
            print(f"Row {i}: Timed out, skipping...")
            results.append({'index': i, 'weather_temp': None, 'weather_humidity': None, 'weather_description': None})

        except requests.exceptions.ConnectionError:
            print(f"Row {i}: Connection error, skipping...")
            results.append({'index': i, 'weather_temp': None, 'weather_humidity': None, 'weather_description': None})

        call_count += 1  # ✅ increment AFTER the request

    else:
        results.append({'index': i, 'weather_temp': None, 'weather_humidity': None, 'weather_description': None})

# Merge back to original df
weather_df = pd.DataFrame(results).set_index('index')
df = pd.concat([df, weather_df], axis=1)

print(f'Available data: {yes} / Total rows: {len(df)}')

Reached 50 calls — waiting 60 seconds...
Resuming...
Row 68: Timed out, skipping...
Reached 100 calls — waiting 60 seconds...
Resuming...
Available data: 119 / Total rows: 144

In [17]:
df

,id,user_id,imported_at,source,garmin_activity_id,api_activity_name,api_activity_type,api_event_type,api_start_time_local,api_start_time_gmt,...,weather_pressure,weather_dew_point,weather_uvi,weather_clouds,weather_visibility,weather_wind_speed,weather_wind_deg,weather_wind_gust,weather_main,weather_rain_1h
0,ff0cdb7a-3dd4-4505-902b-dc5b68a916fa,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175287,garmin_api,24369012997,Treadmill Running,treadmill_running,uncategorized,2026-09-15 18:56:43,2026-09-15 10:56:43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,579307e3-b330-4379-8861-160b19ba0e51,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175293,garmin_api,24327210043,Kuala Lumpur Running,running,uncategorized,2026-09-12 05:43:54,2026-09-11 21:43:54,...,1012.0,299.49,9.84,87.0,10000.0,2.21,232.0,1.51,Clouds,NaN
2,028c4a99-6dfe-4eb2-8385-bbea5306a988,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175296,garmin_api,24315897370,Kuala Lumpur Running,running,uncategorized,2026-09-11 06:27:12,2026-09-10 22:27:12,...,1012.0,299.49,9.84,87.0,10000.0,2.21,232.0,1.51,Clouds,NaN
3,a6d45e37-065f-400c-9e92-e0df067adc98,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175299,garmin_api,24304956583,Treadmill Running,treadmill_running,uncategorized,2026-09-10 12:15:33,2026-09-10 04:15:33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4006480a-3da2-4a04-8659-f27002e0a07f,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175300,garmin_api,24292566213,Treadmill Running,treadmill_running,uncategorized,2026-09-09 12:33:45,2026-09-09 04:33:45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,ae675ab5-590a-4bfa-986a-0807f43beabd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175521,garmin_api,21481902289,Shah Alam Running,running,uncategorized,2026-01-08 20:42:38,2026-01-08 12:42:38,...,1012.0,300.53,5.27,98.0,10000.0,2.19,213.0,1.87,Clouds,NaN
140,67bc0bcb-3d82-4b86-b14e-2d55fc2e699e,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175523,garmin_api,21470473805,Kuala Lumpur Running,running,uncategorized,2026-01-07 18:57:57,2026-01-07 10:57:57,...,1012.0,299.28,9.84,86.0,10000.0,2.35,226.0,1.62,Clouds,NaN
141,ca911597-5b82-47de-ae2e-2b8dd813a404,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175524,garmin_api,21459847472,Kuala Lumpur Running,running,uncategorized,2026-01-06 18:25:26,2026-01-06 10:25:26,...,1012.0,299.30,9.84,86.0,10000.0,2.35,226.0,1.62,Clouds,NaN
142,d60de702-03f4-4e51-ba03-880c14d2d55a,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175525,garmin_api,21448662338,Kuala Lumpur Running,running,uncategorized,2026-01-05 18:19:51,2026-01-05 10:19:51,...,1012.0,299.30,9.84,86.0,10000.0,2.35,226.0,1.62,Clouds,NaN
143,3e9cfb80-ebfa-4005-92e4-435b203428cd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-17 05:15:38.146071,garmin_api,24382041101,Treadmill Running,treadmill_running,uncategorized,2026-09-16 18:35:20,2026-09-16 10:35:20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Weather data convertion
df['weather_temp_celsius'] = round(df['weather_temp'] - 273.17, 2)
df['weather_feels_like_celsius'] = round(df['weather_feels_like'] - 273.17, 2)
df['weather_dew_point_celsius'] = round(df['weather_dew_point'] - 273.17, 2)
df

,id,user_id,imported_at,source,garmin_activity_id,api_activity_name,api_activity_type,api_event_type,api_start_time_local,api_start_time_gmt,...,weather_clouds,weather_visibility,weather_wind_speed,weather_wind_deg,weather_wind_gust,weather_main,weather_rain_1h,weather_temp_celsius,weather_feels_like_celsius,weather_dew_point_celsius
0,ff0cdb7a-3dd4-4505-902b-dc5b68a916fa,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175287,garmin_api,24369012997,Treadmill Running,treadmill_running,uncategorized,2026-09-15 18:56:43,2026-09-15 10:56:43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,579307e3-b330-4379-8861-160b19ba0e51,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175293,garmin_api,24327210043,Kuala Lumpur Running,running,uncategorized,2026-09-12 05:43:54,2026-09-11 21:43:54,...,87.0,10000.0,2.21,232.0,1.51,Clouds,NaN,32.76,39.76,26.32
2,028c4a99-6dfe-4eb2-8385-bbea5306a988,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175296,garmin_api,24315897370,Kuala Lumpur Running,running,uncategorized,2026-09-11 06:27:12,2026-09-10 22:27:12,...,87.0,10000.0,2.21,232.0,1.51,Clouds,NaN,32.76,39.76,26.32
3,a6d45e37-065f-400c-9e92-e0df067adc98,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175299,garmin_api,24304956583,Treadmill Running,treadmill_running,uncategorized,2026-09-10 12:15:33,2026-09-10 04:15:33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4006480a-3da2-4a04-8659-f27002e0a07f,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175300,garmin_api,24292566213,Treadmill Running,treadmill_running,uncategorized,2026-09-09 12:33:45,2026-09-09 04:33:45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,ae675ab5-590a-4bfa-986a-0807f43beabd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175521,garmin_api,21481902289,Shah Alam Running,running,uncategorized,2026-01-08 20:42:38,2026-01-08 12:42:38,...,98.0,10000.0,2.19,213.0,1.87,Clouds,NaN,33.60,40.60,27.36
140,67bc0bcb-3d82-4b86-b14e-2d55fc2e699e,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175523,garmin_api,21470473805,Kuala Lumpur Running,running,uncategorized,2026-01-07 18:57:57,2026-01-07 10:57:57,...,86.0,10000.0,2.35,226.0,1.62,Clouds,NaN,33.06,40.06,26.11
141,ca911597-5b82-47de-ae2e-2b8dd813a404,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175524,garmin_api,21459847472,Kuala Lumpur Running,running,uncategorized,2026-01-06 18:25:26,2026-01-06 10:25:26,...,86.0,10000.0,2.35,226.0,1.62,Clouds,NaN,33.09,40.09,26.13
142,d60de702-03f4-4e51-ba03-880c14d2d55a,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175525,garmin_api,21448662338,Kuala Lumpur Running,running,uncategorized,2026-01-05 18:19:51,2026-01-05 10:19:51,...,86.0,10000.0,2.35,226.0,1.62,Clouds,NaN,33.09,40.09,26.13
143,3e9cfb80-ebfa-4005-92e4-435b203428cd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-17 05:15:38.146071,garmin_api,24382041101,Treadmill Running,treadmill_running,uncategorized,2026-09-16 18:35:20,2026-09-16 10:35:20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# **Finalize Processing**

In [ ]:
to_drop = [
    'source',
    'garmin_activity_id',
    'api_activity_type',
    'api_start_time_gmt',
    'api_bmr_calories',
    'api_max_hr',
    'api_max_running_cadence',
    'api_average_speed',
    'api_max_speed',
    'api_avg_grade_adjusted_speed',
    'api_max_power',
    'api_elevation_loss',
    'api_min_elevation',
    'api_max_elevation',
    'api_end_latitude',
    'api_end_longitude',
    'api_steps',
    'api_lap_count',
    'api_min_temperature',
    'api_max_temperature',
    'api_aerobic_training_effect',
    'api_aerobic_training_effect_message',
    'api_anaerobic_training_effect',
    'api_anaerobic_training_effect_message',
    'api_difference_body_battery',
    'api_is_favorite',
    'api_is_pr',
    'api_device_id',
    'api_manufacturer',
    'pace_mm',
    'mm',
    'ss',
    'dt_unix',
    'weather_temp',
    'weather_description',
    'weather_dt',
    'weather_feels_like',
    'weather_dew_point',
    'weather_wind_gust',
    'weather_rain_1h'
]

for col in to_drop:
    if col in df.columns.tolist():
        # print(f"{col} ✓")
        pass
    else:
        print(f"{col} ✗ NOT FOUND")

In [22]:
df = df.drop(columns=to_drop)
df

,id,user_id,imported_at,api_activity_name,api_event_type,api_start_time_local,api_distance,api_duration,api_elapsed_duration,api_moving_duration,...,weather_dew_point,weather_uvi,weather_clouds,weather_visibility,weather_wind_speed,weather_wind_deg,weather_main,weather_temp_celsius,weather_feels_like_celsius,weather_dew_point_celsius
0,ff0cdb7a-3dd4-4505-902b-dc5b68a916fa,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175287,Treadmill Running,uncategorized,2026-09-15 18:56:43,4060.000000,1945.260010,1945.260010,1943.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,579307e3-b330-4379-8861-160b19ba0e51,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175293,Kuala Lumpur Running,uncategorized,2026-09-12 05:43:54,21114.839844,8362.002930,9173.915039,8346.493988,...,299.49,9.84,87.0,10000.0,2.21,232.0,Clouds,32.76,39.76,26.32
2,028c4a99-6dfe-4eb2-8385-bbea5306a988,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175296,Kuala Lumpur Running,uncategorized,2026-09-11 06:27:12,15313.980469,5998.266113,6416.995117,5990.759003,...,299.49,9.84,87.0,10000.0,2.21,232.0,Clouds,32.76,39.76,26.32
3,a6d45e37-065f-400c-9e92-e0df067adc98,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175299,Treadmill Running,uncategorized,2026-09-10 12:15:33,6191.680176,2864.947998,3209.729004,2862.489990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4006480a-3da2-4a04-8659-f27002e0a07f,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175300,Treadmill Running,uncategorized,2026-09-09 12:33:45,8233.910156,3686.364990,4001.622070,3685.110016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,ae675ab5-590a-4bfa-986a-0807f43beabd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175521,Shah Alam Running,uncategorized,2026-01-08 20:42:38,5018.319824,1721.006958,1721.006958,1719.701996,...,300.53,5.27,98.0,10000.0,2.19,213.0,Clouds,33.60,40.60,27.36
140,67bc0bcb-3d82-4b86-b14e-2d55fc2e699e,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175523,Kuala Lumpur Running,uncategorized,2026-01-07 18:57:57,5124.430176,2665.323975,2665.323975,2663.242035,...,299.28,9.84,86.0,10000.0,2.35,226.0,Clouds,33.06,40.06,26.11
141,ca911597-5b82-47de-ae2e-2b8dd813a404,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175524,Kuala Lumpur Running,uncategorized,2026-01-06 18:25:26,10043.190430,5144.525879,5144.525879,5140.139038,...,299.30,9.84,86.0,10000.0,2.35,226.0,Clouds,33.09,40.09,26.13
142,d60de702-03f4-4e51-ba03-880c14d2d55a,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-16 06:14:20.175525,Kuala Lumpur Running,uncategorized,2026-01-05 18:19:51,5319.750000,1847.706055,1847.706055,1845.068970,...,299.30,9.84,86.0,10000.0,2.35,226.0,Clouds,33.09,40.09,26.13
143,3e9cfb80-ebfa-4005-92e4-435b203428cd,9e2bbfa7-923a-485e-ac55-400c13a0b7d2,2026-09-17 05:15:38.146071,Treadmill Running,uncategorized,2026-09-16 18:35:20,5030.000000,2082.232910,2082.232910,2080.963989,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN